spring:
  application:
    name: demo
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://${DB_URL}?autoReconnect=true&setTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    defer-datasource-initialization: true
